#!/bin/bash


for src in `find dot -name .\*`
do
    dst=${src##*/}
    rm -f "$HOME/$dst"
    echo dotfiles/$src "->" $HOME/$dst
    ln -s "$HOME/dotfiles/$src" "$HOME/$dst"
done

echo "please log off or source ~/.bash_profile"
