#!/bin/bash

DOT_FILES=( .bash_profile  .bashrc  .emacs  .gitconfig  .hgrc  .minttyrc .vimrc )

for file in ${DOT_FILES[@]}
do
    rm -f $HOME/$file
    ln -s $HOME/dotfiles/$file $HOME/$file
    echo dotfiles/$file "->" $HOME/$file
done

echo "please log off or source ~/.bash_profile"
